<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8e130ce5-e75f-4b10-8cf5-b29c3b7cbcdc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CashOverflow.Application\CashOverflow.Application.csproj" />
    <ProjectReference Include="..\CashOverflow.Infrastructure\CashOverflow.Infrastructure.csproj" />
  </ItemGroup>

</Project>
